PENDING = 'PENDING'
RUNNING = 'RUNNING'
FINISHED = 'FINISHED'
FAILED = 'FAILED'
CANCELLED = 'CANCELLED'
STATUS_OPTIONS = (
    (PENDING, 'PENDING'),
    (RUNNING, 'RUNNING'),
    (FINISHED, 'FINISHED'),
    (FAILED, 'FAILED'),
    (CANCELLED, 'CANCELLED'),
)