# Generated by Django 4.0.3 on 2022-03-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0003_alter_analysistool_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(choices=[('Pylint', 'pylint'), ('Pysmell', 'pysmell'), ('PyRef', 'pyref'), ('Vulture', 'vulture'), ('Radon', 'radon')], default='Pylint', max_length=20),
        ),
    ]
