# Generated by Django 4.0.3 on 2022-03-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0004_alter_tool_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='parameters',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
