# Generated by Django 4.0.3 on 2022-03-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0005_alter_tool_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistool',
            name='parameters',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
