# Generated by Django 4.0.3 on 2022-03-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0006_alter_analysistool_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='name',
        ),
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/5384acf426fa419da3833d24b3d7014b', max_length=256),
        ),
    ]
