# Generated by Django 4.0.3 on 2022-03-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0009_alter_analysis_result_alter_analysis_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/17d4ffda308047618f7bd0b6e23b35b9', max_length=256),
        ),
    ]
