# Generated by Django 4.0.3 on 2022-03-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0010_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/28f898a3b19b4292a811c5cc374baa8e', max_length=256),
        ),
    ]
