# Generated by Django 4.0.3 on 2022-03-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0011_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='analysistool',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/e455053315b04be7b0da3d8090bb2b13', max_length=256),
        ),
    ]
