# Generated by Django 4.0.3 on 2022-03-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0012_alter_analysis_status_alter_analysistool_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/c0748524fdfa42cfa2b134a81435b9d2', max_length=256),
        ),
    ]
