# Generated by Django 4.0.3 on 2022-03-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0013_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/85014bd46afb4bbaa85a3753b18dc715', max_length=256),
        ),
    ]
