# Generated by Django 4.0.3 on 2022-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0015_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/3be322516d924191acf92fa1d561d9e0', max_length=256),
        ),
    ]
