# Generated by Django 4.0.3 on 2022-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0017_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/32717c46b7a544a295058ebe836df2d4', max_length=256),
        ),
    ]
