# Generated by Django 4.0.3 on 2022-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0018_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/e02fbdded77c4dbf9a9e06cb931b3e26', max_length=256),
        ),
    ]
