# Generated by Django 4.0.3 on 2022-03-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0021_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/3f3f0afaba004b8a9f9e4c849b619763', max_length=256),
        ),
    ]
