# Generated by Django 4.0.3 on 2022-03-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0022_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/7df187158b754aa88dbaf782e4398c1e', max_length=256),
        ),
    ]
