# Generated by Django 4.0.3 on 2022-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0023_alter_repository_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysistool',
            old_name='analysis_id',
            new_name='analysis',
        ),
        migrations.RenameField(
            model_name='analysistool',
            old_name='tool_id',
            new_name='tool',
        ),
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/aae1aed673744a1b86532f761cdb7faa', max_length=256),
        ),
    ]
