# Generated by Django 4.0.3 on 2022-03-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0024_rename_analysis_id_analysistool_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/508eaddaa33d49c0a66c8c1ca610ef31', max_length=256),
        ),
    ]
