# Generated by Django 4.0.3 on 2022-03-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0025_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/1feeb6a674234c1c898b7efd48dfa2c7', max_length=256),
        ),
    ]
