# Generated by Django 4.0.3 on 2022-03-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0026_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/f90e95b7f2fa40c9a484dd697d2a6d75', max_length=256),
        ),
    ]
