# Generated by Django 4.0.3 on 2022-03-31 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0027_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/03211befa1ec43dd9b3dcb2b78030f29', max_length=256),
        ),
    ]
