# Generated by Django 4.0.3 on 2022-04-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0029_pylinttool_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/2ce014618cc14735a546d09555c60fa3', max_length=256),
        ),
    ]
