# Generated by Django 4.0.3 on 2022-04-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0030_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/00676429781446faa288f4592b8411ee', max_length=256),
        ),
        migrations.DeleteModel(
            name='PylintTool',
        ),
    ]
