# Generated by Django 4.0.3 on 2022-04-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0032_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/a854c171271b49e7b736c36f458b0b8f', max_length=256),
        ),
    ]
