# Generated by Django 4.0.3 on 2022-04-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0033_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/a855ff25e47b40f4921978bbecf3fc24', max_length=256),
        ),
    ]
