# Generated by Django 4.0.3 on 2022-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0036_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/51627eeb603c43a280546038c77b1db8', max_length=256),
        ),
    ]
