# Generated by Django 4.0.3 on 2022-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0037_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/3b1c77243dc248659c6a005b115baf18', max_length=256),
        ),
    ]
