# Generated by Django 4.0.3 on 2022-04-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0038_alter_repository_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='task_id',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_finished',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/fc1bab5d651948e2ae179e98d1e5d334', max_length=256),
        ),
    ]
