# Generated by Django 4.0.3 on 2022-04-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0040_alter_repository_path_celerytasksignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/dd5351ae22474ef38255adc24bfbfdc8', max_length=256),
        ),
    ]
