# Generated by Django 4.0.3 on 2022-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0042_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/c523fec5cefc4b9fa0adb4b6ca937a27', max_length=256),
        ),
    ]
