# Generated by Django 4.0.3 on 2022-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0045_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/f9184df3ce7c4532849c777f3ec306d1', max_length=256),
        ),
    ]
