# Generated by Django 4.0.3 on 2022-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0046_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/821e8ddfddd84775b7880afdd4b5f7b0', max_length=256),
        ),
    ]
