# Generated by Django 4.0.3 on 2022-05-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0047_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/9de6f8e6f06b4e4eb0df54c355f6cade', max_length=256),
        ),
    ]
