# Generated by Django 4.0.3 on 2022-05-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0049_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/e193b2ddc4a74df5871fe32d3dc2ae8e', max_length=256),
        ),
    ]
