# Generated by Django 4.0.3 on 2022-05-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0050_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/f684cb628c90486382b4e3a73a830379', max_length=256),
        ),
    ]
