# Generated by Django 4.0.3 on 2022-05-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0052_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/b8f84f7c9a354ef78a92933b018c9bf0', max_length=256),
        ),
    ]
