# Generated by Django 4.0.3 on 2022-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0053_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/90d6d39d9019428f9bbe45a2240611b6', max_length=256),
        ),
    ]
