# Generated by Django 4.0.3 on 2022-05-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0054_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/5f69c744e2704582a49c63917abceccf', max_length=256),
        ),
    ]
