# Generated by Django 4.0.3 on 2022-05-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0055_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/2a95e33bfd3d45bdb31a0f636dbb64b4', max_length=256),
        ),
    ]
