# Generated by Django 4.0.3 on 2022-05-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0056_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/04a7906993f54558ab5e5ec541255c8e', max_length=256),
        ),
    ]
