# Generated by Django 4.0.3 on 2022-05-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0058_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/7d01b3eae27c42a69c641d706a01a829', max_length=256),
        ),
    ]
