# Generated by Django 4.0.3 on 2022-05-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0059_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/43c2eb59fef440e9b5cda609a46c0e65', max_length=256),
        ),
    ]
