# Generated by Django 4.0.3 on 2022-05-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0060_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/2dde4e7b35b44ca0adc8b26cd6adf9f4', max_length=256),
        ),
    ]
