# Generated by Django 4.0.3 on 2022-05-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0066_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/798dd008880b4b1eab3e06c9ed0eee9f', max_length=256),
        ),
    ]
