# Generated by Django 4.0.3 on 2022-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0067_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/60d4a80dadd849659273cd71366948bb', max_length=256),
        ),
    ]
