# Generated by Django 4.0.3 on 2022-05-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0068_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/24f728b09746429bb5daeb77803484c0', max_length=256),
        ),
    ]
