# Generated by Django 4.0.3 on 2022-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0069_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/30f8fb793ae149fbbcd908dfb7e4a85b', max_length=256),
        ),
    ]
