# Generated by Django 4.0.3 on 2022-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0070_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/648cba75e15244f7bfb57118bc609119', max_length=256),
        ),
    ]
