# Generated by Django 4.0.3 on 2022-05-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0071_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/ef7b9c1c54e5463faf90f16cb4a88450', max_length=256),
        ),
    ]
