# Generated by Django 4.0.3 on 2022-05-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0072_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/91743b5ec58440ae842920f49eecd291', max_length=256),
        ),
    ]
