# Generated by Django 4.0.3 on 2022-05-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0073_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/e11d631997e248b6a55f558099a626ec', max_length=256),
        ),
    ]
