# Generated by Django 4.0.3 on 2022-05-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0074_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/6419efd75f35459ca3b84377876b1504', max_length=256),
        ),
    ]
