# Generated by Django 4.0.3 on 2022-05-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0075_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/4b1f04508d204e0aadf986327d2d9a87', max_length=256),
        ),
    ]
