# Generated by Django 4.0.3 on 2022-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0076_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/0949e02a96e44532a500025e937b5b49', max_length=256),
        ),
    ]
