# Generated by Django 4.0.3 on 2022-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0078_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/b59bed1f96fc4086921306b392e322c9', max_length=256),
        ),
    ]
