# Generated by Django 4.0.3 on 2022-06-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0079_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/dd2809027f9f48e697eaa6ea9b6d6871', max_length=256),
        ),
    ]
