# Generated by Django 4.0.3 on 2022-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0080_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/86b6fc6f84ca47629ff257a3c01bd491', max_length=256),
        ),
    ]
