# Generated by Django 4.0.3 on 2022-06-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0082_alter_repository_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='path',
            field=models.CharField(default='C:/tesis/git/20220603180249818509', max_length=256),
        ),
    ]
