# Generated by Django 4.0.3 on 2022-06-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0083_alter_repository_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='path',
        ),
        migrations.AddField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20220603191344327737', max_length=256),
        ),
    ]
