# Generated by Django 4.0.3 on 2022-06-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0084_remove_repository_path_repository_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20220603191421062521', max_length=256),
        ),
    ]
