# Generated by Django 4.0.3 on 2022-10-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0093_tool_class_name_alter_repository_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysistool',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='python_code_analyzer_app.tool'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20221007184132820101', max_length=256),
        ),
    ]
