# Generated by Django 4.0.3 on 2023-05-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0096_alter_repository_folder_alter_tool_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pylint_Tool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='python_code_analyzer_app.tool')),
            ],
            options={
                'db_table': 'python_code_analyzer_app_tool',
                'managed': False,
            },
            bases=('python_code_analyzer_app.tool',),
        ),
        migrations.CreateModel(
            name='Radon_Tool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='python_code_analyzer_app.tool')),
            ],
            options={
                'db_table': 'python_code_analyzer_app_tool',
                'managed': False,
            },
            bases=('python_code_analyzer_app.tool',),
        ),
        migrations.CreateModel(
            name='Vulture_Tool',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='python_code_analyzer_app.tool')),
            ],
            options={
                'db_table': 'python_code_analyzer_app_tool',
                'managed': False,
            },
            bases=('python_code_analyzer_app.tool',),
        ),
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20230520094146151676', max_length=256),
        ),
        migrations.AlterModelTable(
            name='tool',
            table='python_code_analyzer_app_tool',
        ),
    ]
