# Generated by Django 4.0.3 on 2023-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0097_pylint_tool_radon_tool_vulture_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20230520104807051759', max_length=256),
        ),
    ]
