# Generated by Django 4.0.3 on 2023-05-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0098_alter_repository_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20230522180942275059', max_length=256),
        ),
    ]
