# Generated by Django 4.0.3 on 2023-06-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0100_remove_analysis_result_alter_repository_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='commit',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20230605084307972385', max_length=256),
        ),
    ]
