# Generated by Django 4.0.3 on 2023-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_code_analyzer_app', '0101_alter_analysis_commit_alter_repository_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='parameters',
        ),
        migrations.AlterField(
            model_name='repository',
            name='folder',
            field=models.CharField(default='20230609084946093707', max_length=256),
        ),
    ]
